project:
  type: website
  output-dir: docs
website:
  title: "J. Paul Kelleher"
  navbar:
    left:
      - href: https://paul-kelleher.github.io/
        text: About
      - href: https://paul-kelleher.github.io/research
        text: Research
      - href: https://paul-kelleher.github.io/sccbook
        text: Book
      - href: https://paul-kelleher.github.io/blog
        text: Blog

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    fontsize: 1.125em

editor: visual

