project:
  type: website
  output-dir: docs
website:
  title: "J. Paul Kelleher"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: cv/index.qmd
        text: CV
      - href: research/index.qmd
        text: Research
      - href: sccbook/index.qmd
        text: Book
      - href: https://paul-kelleher.github.io/blog
        text: Blog

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    fontsize: 1.125em
    linestretch: 1.6
    mainfont: "Source Sans Pro, sans-serif"
    monofont: "Source Code Pro, monospace"


editor: visual

